### ISSUE TITLE
The Sheets Name Field Mapping field doesn't persist in the UI - even though it works in the overall experience

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#43] opened 2024-12-13 10:49 UTC
![image](https://github.com/user-attachments/assets/c74a9095-d047-4dfc-a7e7-f0ad3fa9aa5e)
![image](https://github.com/user-attachments/assets/9703777e-c52a-4697-a8ce-896b4e72a82d)

The name field mapping is clearly right, but the field mapping selection doesn't persist in the Sheets (template) editor.

**Comment by sunbeam60** [comment] 2024-12-13 10:53
Sorry I'm not sure my bug description is super clear. See here:

https://github.com/user-attachments/assets/7e958ec6-1356-4b26-8484-98196647152c

**Comment by Heilemann** [comment] 2024-12-14 21:55
The tales I could tell about trying to find the cause of this. I have no idea, is the short answer. But it did make me realize that I need to basically excise GraphQL, which the fix for this is the beginning of.

Fix going to prod shortly.

**Closed by Heilemann** 2024-12-14 21:55 UTC
